### ISSUE TITLE
loop終了後のエラーについて

### ISSUE THREAD

**Issue by mmochizuki** [kumitatepazuru/cszp#7]
再インストールを行ったところ、loopモードで30試合を実行することができ、
CSVファイルに30試合分の試合結果を記録するところまではできました。

ただし、30試合が終了した時点で下記のエラーが出てしまったので報告します。

---------- 2019/12/14 21:22:20 -----------
mkdir: ディレクトリ `./html_logs/20191214_212219' を作成できません: そのようなファイルやディレクトリはありません
Traceback (most recent call last):
  File "/opt/cszp/main.py", line 139, in <module>
    main()
  File "/opt/cszp/main.py", line 105, in main
    r = cszp_menu.menu_jp()
  File "/opt/cszp/cszp_menu.py", line 86, in menu_jp
    cszp_soccer.setting_jp_loop()
  File "/opt/cszp/cszp_soccer.py", line 1141, in setting_jp_loop
    loop(cmd, loops)
  File "/opt/cszp/cszp_soccer.py", line 188, in loop
    cszp_html.logs(exittime)
  File "/opt/cszp/cszp_html.py", line 55, in logs
    subprocess.check_call("mkdir ./html_logs/" + time, shell=True)
  File "/home/mm/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mkdir ./html_logs/20191214_212219' returned non-zero exit status 1.

**Comment by kumitatepazuru** [comment]
直しました。
