### ISSUE TITLE
実行後にImportError: No module named '_tkinter'

### ISSUE THREAD

**Issue by masayoshi-nakamura** [kumitatepazuru/cszp#9]
```
                               ___  ___  ____ _ __   |___ \    / |   / _ \ 
                              / __|/ __||_  /| '_ \    __) |   | |  | | | |
                             | (__ \__ \ / / | |_) |  / __/  _ | | _| |_| |
                              \___||___//___|| .__/  |_____|(_)|_|(_)\___/ 
                                             |_|                           

[OK] pythonVersion:3.5.2
loading Now...
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 36, in <module>
    import _tkinter
ImportError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt//cszp/main.py", line 140, in <module>
    main()
  File "/opt//cszp/main.py", line 100, in main
    import cszp_menu
  File "/opt/cszp/cszp_menu.py", line 9, in <module>
    import cszp_soccer
  File "/opt/cszp/cszp_soccer.py", line 9, in <module>
    import cszp_html
  File "/opt/cszp/cszp_html.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 2372, in <module>
    switch_backend(rcParams["backend"])
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/_backend_tk.py", line 5, in <module>
    import tkinter as Tk
  File "/usr/lib/python3.5/tkinter/__init__.py", line 38, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package
```

**Comment by kumitatepazuru** [comment]
一応
sudo apt install python3-tk
で動くはずです.
一応閉じておきますが何かあればコメントください

**Comment by kumitatepazuru** [comment]
一応
sudo apt install python3-tk
で動くはずです

**Comment by masayoshi-nakamura** [comment]
ありがとうございます。できました
